/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UdharRouteImport } from './routes/udhar'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SalesInvoiceRouteImport } from './routes/sales-invoice'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PosRouteImport } from './routes/pos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CashbookRouteImport } from './routes/cashbook'
import { Route as IndexRouteImport } from './routes/index'

const UdharRoute = UdharRouteImport.update({
  id: '/udhar',
  path: '/udhar',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesInvoiceRoute = SalesInvoiceRouteImport.update({
  id: '/sales-invoice',
  path: '/sales-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CashbookRoute = CashbookRouteImport.update({
  id: '/cashbook',
  path: '/cashbook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cashbook': typeof CashbookRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/purchase': typeof PurchaseRoute
  '/reports': typeof ReportsRoute
  '/sales-invoice': typeof SalesInvoiceRoute
  '/suppliers': typeof SuppliersRoute
  '/udhar': typeof UdharRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cashbook': typeof CashbookRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/purchase': typeof PurchaseRoute
  '/reports': typeof ReportsRoute
  '/sales-invoice': typeof SalesInvoiceRoute
  '/suppliers': typeof SuppliersRoute
  '/udhar': typeof UdharRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cashbook': typeof CashbookRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/purchase': typeof PurchaseRoute
  '/reports': typeof ReportsRoute
  '/sales-invoice': typeof SalesInvoiceRoute
  '/suppliers': typeof SuppliersRoute
  '/udhar': typeof UdharRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cashbook'
    | '/customers'
    | '/expenses'
    | '/inventory'
    | '/login'
    | '/pos'
    | '/products'
    | '/purchase'
    | '/reports'
    | '/sales-invoice'
    | '/suppliers'
    | '/udhar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cashbook'
    | '/customers'
    | '/expenses'
    | '/inventory'
    | '/login'
    | '/pos'
    | '/products'
    | '/purchase'
    | '/reports'
    | '/sales-invoice'
    | '/suppliers'
    | '/udhar'
  id:
    | '__root__'
    | '/'
    | '/cashbook'
    | '/customers'
    | '/expenses'
    | '/inventory'
    | '/login'
    | '/pos'
    | '/products'
    | '/purchase'
    | '/reports'
    | '/sales-invoice'
    | '/suppliers'
    | '/udhar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashbookRoute: typeof CashbookRoute
  CustomersRoute: typeof CustomersRoute
  ExpensesRoute: typeof ExpensesRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  PosRoute: typeof PosRoute
  ProductsRoute: typeof ProductsRoute
  PurchaseRoute: typeof PurchaseRoute
  ReportsRoute: typeof ReportsRoute
  SalesInvoiceRoute: typeof SalesInvoiceRoute
  SuppliersRoute: typeof SuppliersRoute
  UdharRoute: typeof UdharRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/udhar': {
      id: '/udhar'
      path: '/udhar'
      fullPath: '/udhar'
      preLoaderRoute: typeof UdharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-invoice': {
      id: '/sales-invoice'
      path: '/sales-invoice'
      fullPath: '/sales-invoice'
      preLoaderRoute: typeof SalesInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashbook': {
      id: '/cashbook'
      path: '/cashbook'
      fullPath: '/cashbook'
      preLoaderRoute: typeof CashbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashbookRoute: CashbookRoute,
  CustomersRoute: CustomersRoute,
  ExpensesRoute: ExpensesRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  PosRoute: PosRoute,
  ProductsRoute: ProductsRoute,
  PurchaseRoute: PurchaseRoute,
  ReportsRoute: ReportsRoute,
  SalesInvoiceRoute: SalesInvoiceRoute,
  SuppliersRoute: SuppliersRoute,
  UdharRoute: UdharRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
